all:
  hosts:
    local:
      ansible_python_interpreter: auto_silent
      ansible_connection: local
      disk:
        wipe: true
        partitions:
          - device: '/dev/vda'
            boot: yes
            part_start: '1MiB'
            part_end: '1024MiB'
            # mountpoint: '/boot' <- default, if boot true
          # - device: '/dev/vda'
          #   fs_type: 'btrfs'
          #   flags: ['b']
    chroot:
      ansible_python_interpreter: auto_silent
      ansible_connection: community.general.chroot
      ansible_chroot_exe: arch-chroot
      ansible_executable: bash
      ansible_host: /mnt/archinstall
