---

all:
  hosts:
    local:
      ansible_python_interpreter: auto_silent
      ansible_connection: local
    chroot:
      ansible_python_interpreter: auto_silent
      ansible_connection: community.general.chroot
      ansible_chroot_exe: arch-chroot
      ansible_executable: bash
      ansible_host: /mnt/archinstall
  vars:
    archinstall:
      target: '/mnt/archinstall'
      hostname: 'arch-s15'
      multilib: true
      reflector:
        timer: true
        timeout_secs: 3600
        args: '-c KZ, -p http --completion-percent 99 -f 5 --save /etc/pacman.d/mirrorlist'
      kernels: zen,lts
      # kernels:
      #   linux: 0
      #   zen: default
      #   lts: true
      pacstrap_packages:
        - terminus-font
        - networkmanager
        - man-db
        - man-pages
        - ansible
        - git
        - neovim
      btrfs: true
      swap: true
      timezone: 'Asia/Almaty'
      locales:
        - en_US.UTF-8 UTF-8
        - ru_RU.UTF-8 UTF-8
        - kk_KZ.UTF-8 UTF-8
      vconsole:
        keymap: ru
        font: ter-p22n
