---

all:
  hosts:
    local:
      ansible_python_interpreter: auto_silent
      ansible_connection: local
      archinstall:
        multilib: true
        reflector:
          timer: true
          args: '-c KZ, -p http --completion-percent 99 -f 5 --save /etc/pacman.d/mirrorlist'
    chroot:
      ansible_python_interpreter: auto_silent
      ansible_connection: community.general.chroot
      ansible_chroot_exe: arch-chroot
      ansible_executable: bash
      ansible_host: /mnt/archinstall
