---

all:
  hosts:
    local:
      ansible_python_interpreter: auto_silent
      ansible_connection: local
    chroot:
      ansible_python_interpreter: auto_silent
      ansible_connection: community.general.chroot
      ansible_chroot_exe: arch-chroot
      ansible_executable: bash
      ansible_host: /mnt/archinstall
  vars:
    archinstall:
      target: '/mnt/archinstall'
      multilib: true
      reflector:
        timer: true
        timeout_secs: 3600
        args: '-c KZ, -p http --completion-percent 99 -f 5 --save /etc/pacman.d/mirrorlist'
      kernels: zen,lts
      # kernels:
      #   linux: 0
      #   zen: default
      #   lts: true
      btrfs: true
      swap: true
