---

all:
  hosts:
    local:
      ansible_python_interpreter: auto_silent
      ansible_connection: local
    chroot:
      ansible_python_interpreter: auto_silent
      ansible_connection: community.general.chroot
      ansible_chroot_exe: arch-chroot
      ansible_executable: bash
      ansible_host: /mnt/archinstall
