---

all:
  hosts:
    local:
      ansible_python_interpreter: auto_silent
      ansible_connection: local
      disk:
        wipe: true
        partitions:
          - device: '/dev/vda'
            label: 'BOOT'
            boot: true
            part_start: '1MiB'
            part_end: '512MiB'
            # mountpoint: '/boot' <- default, if boot true
          - device: '/dev/vda'
            label: 'root'
            part_start: '513MiB'
            part_end: '100%'
            fs_type: 'btrfs'
    chroot:
      ansible_python_interpreter: auto_silent
      ansible_connection: community.general.chroot
      ansible_chroot_exe: arch-chroot
      ansible_executable: bash
      ansible_host: /mnt/archinstall
