---

all:
  hosts:
    local:
      ansible_python_interpreter: auto_silent
      ansible_connection: local
    chroot:
      ansible_python_interpreter: auto_silent
      ansible_connection: community.general.chroot
      ansible_chroot_exe: arch-chroot
      ansible_executable: bash
      ansible_host: /mnt
  vars:
    archinstall:
      target: '/mnt'
      hostname: 'arch-t16'
      processor: 'amd'
      kernels: zen,lts
      # kernels:
      #   linux: 0
      #   zen: default
      #   lts: true
      mkinitcpio:
      #   modules: 'crc32c-intel intel_agp i915'
      #   binaries: ''
      #   files: ''
      #   hooks: 'base consolefont udev autodetect modconf block filesystems keyboard fsck'
      #   compression: 'zstd'
      bootloader:
        grub: true
        part_selector: '{{ part_selector }}'
        fstype: 'btrfs'
        subvol_selector: 'subvol=/@'
        # kernel_params: 'sysrq_always_enabled=1 snd_hda_codec_hdmi.enable_silent_stream=0'
        kernel_params: 'sysrq_always_enabled=1'
        timeout: 1
        timeout_style: hidden
        # editor: true
      reflector:
        timer: true
        timeout_secs: 3600
        args: '-c KZ, -p http --completion-percent 99 -f 5 --save /etc/pacman.d/mirrorlist'
      pacstrap_packages:
        - amd-ucode
        - realtime-privileges
      btrfs: true
      swap: true
      timezone: 'Asia/Almaty'
      locales:
        - en_US.UTF-8 UTF-8
        - ru_RU.UTF-8 UTF-8
        - kk_KZ.UTF-8 UTF-8
      vconsole:
        keymap: ru
        font: ter-p22n
      users:
        - name: zhanibek
          shell: /usr/bin/zsh
          groups:
            - wheel
            - realtime
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            64653562396532613562366433336562636231376331383466386438636364623165386536613436
            3837643831643561306138393761303530333336613134330a376438386331383465373962653237
            37393039356534363232316334313766653636323439393063616438363732313863623938383831
            3738363134396133610a353437623139333932626563376132333337333061633535393932383465
            6532
