all:
  hosts:
    default:
      ansible_python_interpreter: auto_silent
      ansible_host: localhost
      ansible_port: 22222
      ansible_user: root
      ansible_ssh_pass: asdf
      ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
